package com.ipaynow.sdk.api.dto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reqParamProto.proto

public final class ReqParamProto {
  private ReqParamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code METHOD}
   */
  public enum METHOD
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PAY = 0;</code>
     */
    PAY(0),
    /**
     * <code>RECEIVE = 1;</code>
     */
    RECEIVE(1),
    /**
     * <code>QUERY_TRANS = 2;</code>
     */
    QUERY_TRANS(2),
    /**
     * <code>QUERY_BALANCE = 3;</code>
     */
    QUERY_BALANCE(3),
    /**
     * <code>TRANS = 4;</code>
     */
    TRANS(4),
    /**
     * <code>QUERY_TRANS_DETAIL = 5;</code>
     */
    QUERY_TRANS_DETAIL(5),
    /**
     * <code>QUERY_BALANCE_V1 = 6;</code>
     */
    QUERY_BALANCE_V1(6),
    /**
     * <code>AGENT_PAY_REFUND_QUERY = 7;</code>
     */
    AGENT_PAY_REFUND_QUERY(7),
    /**
     * <code>AGENT_PAY_REFUND_BATCH_QUERY = 8;</code>
     */
    AGENT_PAY_REFUND_BATCH_QUERY(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PAY = 0;</code>
     */
    public static final int PAY_VALUE = 0;
    /**
     * <code>RECEIVE = 1;</code>
     */
    public static final int RECEIVE_VALUE = 1;
    /**
     * <code>QUERY_TRANS = 2;</code>
     */
    public static final int QUERY_TRANS_VALUE = 2;
    /**
     * <code>QUERY_BALANCE = 3;</code>
     */
    public static final int QUERY_BALANCE_VALUE = 3;
    /**
     * <code>TRANS = 4;</code>
     */
    public static final int TRANS_VALUE = 4;
    /**
     * <code>QUERY_TRANS_DETAIL = 5;</code>
     */
    public static final int QUERY_TRANS_DETAIL_VALUE = 5;
    /**
     * <code>QUERY_BALANCE_V1 = 6;</code>
     */
    public static final int QUERY_BALANCE_V1_VALUE = 6;
    /**
     * <code>AGENT_PAY_REFUND_QUERY = 7;</code>
     */
    public static final int AGENT_PAY_REFUND_QUERY_VALUE = 7;
    /**
     * <code>AGENT_PAY_REFUND_BATCH_QUERY = 8;</code>
     */
    public static final int AGENT_PAY_REFUND_BATCH_QUERY_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static METHOD valueOf(int value) {
      return forNumber(value);
    }

    public static METHOD forNumber(int value) {
      switch (value) {
        case 0: return PAY;
        case 1: return RECEIVE;
        case 2: return QUERY_TRANS;
        case 3: return QUERY_BALANCE;
        case 4: return TRANS;
        case 5: return QUERY_TRANS_DETAIL;
        case 6: return QUERY_BALANCE_V1;
        case 7: return AGENT_PAY_REFUND_QUERY;
        case 8: return AGENT_PAY_REFUND_BATCH_QUERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<METHOD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        METHOD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<METHOD>() {
            public METHOD findValueByNumber(int number) {
              return METHOD.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ReqParamProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final METHOD[] VALUES = values();

    public static METHOD valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private METHOD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:METHOD)
  }

  public interface ParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Param)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.METHOD method = 1;</code>
     */
    int getMethodValue();
    /**
     * <code>.METHOD method = 1;</code>
     */
    ReqParamProto.METHOD getMethod();

    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    boolean hasSign();
    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    TransactionProto.SignedTransaction getSign();
    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    TransactionProto.SignedTransactionOrBuilder getSignOrBuilder();
  }
  /**
   * Protobuf type {@code Param}
   */
  public  static final class Param extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Param)
      ParamOrBuilder {
    // Use Param.newBuilder() to construct.
    private Param(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Param() {
      method_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Param(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              method_ = rawValue;
              break;
            }
            case 18: {
              TransactionProto.SignedTransaction.Builder subBuilder = null;
              if (sign_ != null) {
                subBuilder = sign_.toBuilder();
              }
              sign_ = input.readMessage(TransactionProto.SignedTransaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sign_);
                sign_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReqParamProto.internal_static_Param_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReqParamProto.internal_static_Param_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReqParamProto.Param.class, ReqParamProto.Param.Builder.class);
    }

    public static final int METHOD_FIELD_NUMBER = 1;
    private int method_;
    /**
     * <code>.METHOD method = 1;</code>
     */
    public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.METHOD method = 1;</code>
     */
    public ReqParamProto.METHOD getMethod() {
      ReqParamProto.METHOD result = ReqParamProto.METHOD.valueOf(method_);
      return result == null ? ReqParamProto.METHOD.UNRECOGNIZED : result;
    }

    public static final int SIGN_FIELD_NUMBER = 2;
    private TransactionProto.SignedTransaction sign_;
    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    public boolean hasSign() {
      return sign_ != null;
    }
    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    public TransactionProto.SignedTransaction getSign() {
      return sign_ == null ? TransactionProto.SignedTransaction.getDefaultInstance() : sign_;
    }
    /**
     * <code>.SignedTransaction sign = 2;</code>
     */
    public TransactionProto.SignedTransactionOrBuilder getSignOrBuilder() {
      return getSign();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (method_ != ReqParamProto.METHOD.PAY.getNumber()) {
        output.writeEnum(1, method_);
      }
      if (sign_ != null) {
        output.writeMessage(2, getSign());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (method_ != ReqParamProto.METHOD.PAY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, method_);
      }
      if (sign_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSign());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReqParamProto.Param)) {
        return super.equals(obj);
      }
      ReqParamProto.Param other = (ReqParamProto.Param) obj;

      boolean result = true;
      result = result && method_ == other.method_;
      result = result && (hasSign() == other.hasSign());
      if (hasSign()) {
        result = result && getSign()
            .equals(other.getSign());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + method_;
      if (hasSign()) {
        hash = (37 * hash) + SIGN_FIELD_NUMBER;
        hash = (53 * hash) + getSign().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReqParamProto.Param parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqParamProto.Param parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqParamProto.Param parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqParamProto.Param parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqParamProto.Param parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqParamProto.Param parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqParamProto.Param parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReqParamProto.Param parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqParamProto.Param parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqParamProto.Param parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReqParamProto.Param prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Param}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Param)
        ReqParamProto.ParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReqParamProto.internal_static_Param_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReqParamProto.internal_static_Param_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReqParamProto.Param.class, ReqParamProto.Param.Builder.class);
      }

      // Construct using com.ipaynow.sdk.api.dto.ReqParamProto.Param.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        method_ = 0;

        if (signBuilder_ == null) {
          sign_ = null;
        } else {
          sign_ = null;
          signBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReqParamProto.internal_static_Param_descriptor;
      }

      public ReqParamProto.Param getDefaultInstanceForType() {
        return ReqParamProto.Param.getDefaultInstance();
      }

      public ReqParamProto.Param build() {
        ReqParamProto.Param result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReqParamProto.Param buildPartial() {
        ReqParamProto.Param result = new ReqParamProto.Param(this);
        result.method_ = method_;
        if (signBuilder_ == null) {
          result.sign_ = sign_;
        } else {
          result.sign_ = signBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReqParamProto.Param) {
          return mergeFrom((ReqParamProto.Param)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReqParamProto.Param other) {
        if (other == ReqParamProto.Param.getDefaultInstance()) return this;
        if (other.method_ != 0) {
          setMethodValue(other.getMethodValue());
        }
        if (other.hasSign()) {
          mergeSign(other.getSign());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReqParamProto.Param parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReqParamProto.Param) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int method_ = 0;
      /**
       * <code>.METHOD method = 1;</code>
       */
      public int getMethodValue() {
        return method_;
      }
      /**
       * <code>.METHOD method = 1;</code>
       */
      public Builder setMethodValue(int value) {
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.METHOD method = 1;</code>
       */
      public ReqParamProto.METHOD getMethod() {
        ReqParamProto.METHOD result = ReqParamProto.METHOD.valueOf(method_);
        return result == null ? ReqParamProto.METHOD.UNRECOGNIZED : result;
      }
      /**
       * <code>.METHOD method = 1;</code>
       */
      public Builder setMethod(ReqParamProto.METHOD value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        method_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.METHOD method = 1;</code>
       */
      public Builder clearMethod() {
        
        method_ = 0;
        onChanged();
        return this;
      }

      private TransactionProto.SignedTransaction sign_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionProto.SignedTransaction, TransactionProto.SignedTransaction.Builder, TransactionProto.SignedTransactionOrBuilder> signBuilder_;
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public boolean hasSign() {
        return signBuilder_ != null || sign_ != null;
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public TransactionProto.SignedTransaction getSign() {
        if (signBuilder_ == null) {
          return sign_ == null ? TransactionProto.SignedTransaction.getDefaultInstance() : sign_;
        } else {
          return signBuilder_.getMessage();
        }
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public Builder setSign(TransactionProto.SignedTransaction value) {
        if (signBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sign_ = value;
          onChanged();
        } else {
          signBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public Builder setSign(
          TransactionProto.SignedTransaction.Builder builderForValue) {
        if (signBuilder_ == null) {
          sign_ = builderForValue.build();
          onChanged();
        } else {
          signBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public Builder mergeSign(TransactionProto.SignedTransaction value) {
        if (signBuilder_ == null) {
          if (sign_ != null) {
            sign_ =
              TransactionProto.SignedTransaction.newBuilder(sign_).mergeFrom(value).buildPartial();
          } else {
            sign_ = value;
          }
          onChanged();
        } else {
          signBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public Builder clearSign() {
        if (signBuilder_ == null) {
          sign_ = null;
          onChanged();
        } else {
          sign_ = null;
          signBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public TransactionProto.SignedTransaction.Builder getSignBuilder() {
        
        onChanged();
        return getSignFieldBuilder().getBuilder();
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      public TransactionProto.SignedTransactionOrBuilder getSignOrBuilder() {
        if (signBuilder_ != null) {
          return signBuilder_.getMessageOrBuilder();
        } else {
          return sign_ == null ?
              TransactionProto.SignedTransaction.getDefaultInstance() : sign_;
        }
      }
      /**
       * <code>.SignedTransaction sign = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionProto.SignedTransaction, TransactionProto.SignedTransaction.Builder, TransactionProto.SignedTransactionOrBuilder> 
          getSignFieldBuilder() {
        if (signBuilder_ == null) {
          signBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransactionProto.SignedTransaction, TransactionProto.SignedTransaction.Builder, TransactionProto.SignedTransactionOrBuilder>(
                  getSign(),
                  getParentForChildren(),
                  isClean());
          sign_ = null;
        }
        return signBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Param)
    }

    // @@protoc_insertion_point(class_scope:Param)
    private static final ReqParamProto.Param DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReqParamProto.Param();
    }

    public static ReqParamProto.Param getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Param>
        PARSER = new com.google.protobuf.AbstractParser<Param>() {
      public Param parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Param(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Param> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Param> getParserForType() {
      return PARSER;
    }

    public ReqParamProto.Param getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Param_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Param_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023reqParamProto.proto\032\026transactionProto." +
      "proto\"B\n\005Param\022\027\n\006method\030\001 \001(\0162\007.METHOD\022" +
      " \n\004sign\030\002 \001(\0132\022.SignedTransaction*\271\001\n\006ME" +
      "THOD\022\007\n\003PAY\020\000\022\013\n\007RECEIVE\020\001\022\017\n\013QUERY_TRAN" +
      "S\020\002\022\021\n\rQUERY_BALANCE\020\003\022\t\n\005TRANS\020\004\022\026\n\022QUE" +
      "RY_TRANS_DETAIL\020\005\022\024\n\020QUERY_BALANCE_V1\020\006\022" +
      "\032\n\026AGENT_PAY_REFUND_QUERY\020\007\022 \n\034AGENT_PAY" +
      "_REFUND_BATCH_QUERY\020\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TransactionProto.getDescriptor(),
        }, assigner);
    internal_static_Param_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Param_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Param_descriptor,
        new java.lang.String[] { "Method", "Sign", });
    TransactionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
