package com.ipaynow.sdk.api.dto;// Generated by the protocol buffer compiler. DO NOT EDIT!

// source: transactionProto.proto

public final class TransactionProto {

    private TransactionProto(){
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code Crypto}
     */
    public enum Crypto implements com.google.protobuf.ProtocolMessageEnum {
                                                                           /**
                                                                            * <code>SECP = 0;</code>
                                                                            */
                                                                           SECP(0),
                                                                           /**
                                                                            * <code>SM2 = 1;</code>
                                                                            */
                                                                           SM2(1), UNRECOGNIZED(-1),;

        /**
         * <code>SECP = 0;</code>
         */
        public static final int SECP_VALUE = 0;
        /**
         * <code>SM2 = 1;</code>
         */
        public static final int SM2_VALUE  = 1;

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Crypto valueOf(int value) {
            return forNumber(value);
        }

        public static Crypto forNumber(int value) {
            switch (value) {
                case 0:
                    return SECP;
                case 1:
                    return SM2;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Crypto> internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<Crypto> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Crypto>() {

            public Crypto findValueByNumber(int number) {
                return Crypto.forNumber(number);
            }
        };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
            return TransactionProto.getDescriptor().getEnumTypes().get(0);
        }

        private static final Crypto[] VALUES = values();

        public static Crypto valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Crypto(int value){
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Crypto)
    }

    public interface TransactionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Transaction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string from = 1;</code>
         */
        java.lang.String getFrom();

        /**
         * <code>string from = 1;</code>
         */
        com.google.protobuf.ByteString getFromBytes();

        /**
         * <code>string to = 2;</code>
         */
        java.lang.String getTo();

        /**
         * <code>string to = 2;</code>
         */
        com.google.protobuf.ByteString getToBytes();

        /**
         * <code>bytes content = 3;</code>
         */
        com.google.protobuf.ByteString getContent();
    }

    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Transaction extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Transaction)
            TransactionOrBuilder {

        // Use Transaction.newBuilder() to construct.
        private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder){
            super(builder);
        }

        private Transaction(){
            from_ = "";
            to_ = "3";
            content_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Transaction(com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException{
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            from_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            to_ = s;
                            break;
                        }
                        case 26: {

                            content_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return TransactionProto.internal_static_Transaction_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return TransactionProto.internal_static_Transaction_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.Transaction.class,
                                                                                                                   TransactionProto.Transaction.Builder.class);
        }

        public static final int           FROM_FIELD_NUMBER = 1;
        private volatile java.lang.Object from_;

        /**
         * <code>string from = 1;</code>
         */
        public java.lang.String getFrom() {
            java.lang.Object ref = from_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                from_ = s;
                return s;
            }
        }

        /**
         * <code>string from = 1;</code>
         */
        public com.google.protobuf.ByteString getFromBytes() {
            java.lang.Object ref = from_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                from_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int           TO_FIELD_NUMBER = 2;
        private volatile java.lang.Object to_;

        /**
         * <code>string to = 2;</code>
         */
        public java.lang.String getTo() {
            java.lang.Object ref = to_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                to_ = s;
                return s;
            }
        }

        /**
         * <code>string to = 2;</code>
         */
        public com.google.protobuf.ByteString getToBytes() {
            java.lang.Object ref = to_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                to_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int                CONTENT_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString content_;

        /**
         * <code>bytes content = 3;</code>
         */
        public com.google.protobuf.ByteString getContent() {
            return content_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getFromBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
            }
            if (!getToBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
            }
            if (!content_.isEmpty()) {
                output.writeBytes(3, content_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getFromBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
            }
            if (!getToBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
            }
            if (!content_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, content_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TransactionProto.Transaction)) {
                return super.equals(obj);
            }
            TransactionProto.Transaction other = (TransactionProto.Transaction) obj;

            boolean result = true;
            result = result && getFrom().equals(other.getFrom());
            result = result && getTo().equals(other.getTo());
            result = result && getContent().equals(other.getContent());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + FROM_FIELD_NUMBER;
            hash = (53 * hash) + getFrom().hashCode();
            hash = (37 * hash) + TO_FIELD_NUMBER;
            hash = (53 * hash) + getTo().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TransactionProto.Transaction parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.Transaction parseFrom(com.google.protobuf.ByteString data,
                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.Transaction parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.Transaction parseFrom(byte[] data,
                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.Transaction parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.Transaction parseFrom(java.io.InputStream input,
                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TransactionProto.Transaction parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static TransactionProto.Transaction parseDelimitedFrom(java.io.InputStream input,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                                                                                        extensionRegistry);
        }

        public static TransactionProto.Transaction parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.Transaction parseFrom(com.google.protobuf.CodedInputStream input,
                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TransactionProto.Transaction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Transaction}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Transaction)
                TransactionProto.TransactionOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return TransactionProto.internal_static_Transaction_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return TransactionProto.internal_static_Transaction_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.Transaction.class,
                                                                                                                       TransactionProto.Transaction.Builder.class);
            }

            // Construct using com.ipaynow.sdk.api.dto.TransactionProto.Transaction.newBuilder()
            private Builder(){
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent){
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                from_ = "";

                to_ = "";

                content_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return TransactionProto.internal_static_Transaction_descriptor;
            }

            public TransactionProto.Transaction getDefaultInstanceForType() {
                return TransactionProto.Transaction.getDefaultInstance();
            }

            public TransactionProto.Transaction build() {
                TransactionProto.Transaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TransactionProto.Transaction buildPartial() {
                TransactionProto.Transaction result = new TransactionProto.Transaction(this);
                result.from_ = from_;
                result.to_ = to_;
                result.content_ = content_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TransactionProto.Transaction) {
                    return mergeFrom((TransactionProto.Transaction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TransactionProto.Transaction other) {
                if (other == TransactionProto.Transaction.getDefaultInstance()) return this;
                if (!other.getFrom().isEmpty()) {
                    from_ = other.from_;
                    onChanged();
                }
                if (!other.getTo().isEmpty()) {
                    to_ = other.to_;
                    onChanged();
                }
                if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
                    setContent(other.getContent());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                TransactionProto.Transaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TransactionProto.Transaction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object from_ = "";

            /**
             * <code>string from = 1;</code>
             */
            public java.lang.String getFrom() {
                java.lang.Object ref = from_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    from_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string from = 1;</code>
             */
            public com.google.protobuf.ByteString getFromBytes() {
                java.lang.Object ref = from_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    from_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string from = 1;</code>
             */
            public Builder setFrom(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                from_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string from = 1;</code>
             */
            public Builder clearFrom() {

                from_ = getDefaultInstance().getFrom();
                onChanged();
                return this;
            }

            /**
             * <code>string from = 1;</code>
             */
            public Builder setFromBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                from_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object to_ = "3";

            /**
             * <code>string to = 2;</code>
             */
            public java.lang.String getTo() {
                java.lang.Object ref = to_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    to_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string to = 2;</code>
             */
            public com.google.protobuf.ByteString getToBytes() {
                java.lang.Object ref = to_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    to_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string to = 2;</code>
             */
            public Builder setTo(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                to_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string to = 2;</code>
             */
            public Builder clearTo() {

                to_ = getDefaultInstance().getTo();
                onChanged();
                return this;
            }

            /**
             * <code>string to = 2;</code>
             */
            public Builder setToBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                to_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes content = 3;</code>
             */
            public com.google.protobuf.ByteString getContent() {
                return content_;
            }

            /**
             * <code>bytes content = 3;</code>
             */
            public Builder setContent(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes content = 3;</code>
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Transaction)
        }

        // @@protoc_insertion_point(class_scope:Transaction)
        private static final TransactionProto.Transaction DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new TransactionProto.Transaction();
        }

        public static TransactionProto.Transaction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Transaction> PARSER = new com.google.protobuf.AbstractParser<Transaction>() {

            public Transaction parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Transaction(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Transaction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Transaction> getParserForType() {
            return PARSER;
        }

        public TransactionProto.Transaction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ContentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Content)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string nonce = 1;</code>
         */
        java.lang.String getNonce();

        /**
         * <code>string nonce = 1;</code>
         */
        com.google.protobuf.ByteString getNonceBytes();

        /**
         * <code>uint64 gas = 2;</code>
         */
        long getGas();

        /**
         * <code>uint64 value = 3;</code>
         */
        long getValue();

        /**
         * <code>bytes data = 4;</code>
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * Protobuf type {@code Content}
     */
    public static final class Content extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Content)
            ContentOrBuilder {

        // Use Content.newBuilder() to construct.
        private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder){
            super(builder);
        }

        private Content(){
            nonce_ = "";
            gas_ = 0L;
            value_ = 0L;
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Content(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException{
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            nonce_ = s;
                            break;
                        }
                        case 16: {

                            gas_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            value_ = input.readUInt64();
                            break;
                        }
                        case 34: {

                            data_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return TransactionProto.internal_static_Content_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return TransactionProto.internal_static_Content_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.Content.class,
                                                                                                               TransactionProto.Content.Builder.class);
        }

        public static final int           NONCE_FIELD_NUMBER = 1;
        private volatile java.lang.Object nonce_;

        /**
         * <code>string nonce = 1;</code>
         */
        public java.lang.String getNonce() {
            java.lang.Object ref = nonce_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                nonce_ = s;
                return s;
            }
        }

        /**
         * <code>string nonce = 1;</code>
         */
        public com.google.protobuf.ByteString getNonceBytes() {
            java.lang.Object ref = nonce_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                nonce_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int GAS_FIELD_NUMBER = 2;
        private long            gas_;

        /**
         * <code>uint64 gas = 2;</code>
         */
        public long getGas() {
            return gas_;
        }

        public static final int VALUE_FIELD_NUMBER = 3;
        private long            value_;

        /**
         * <code>uint64 value = 3;</code>
         */
        public long getValue() {
            return value_;
        }

        public static final int                DATA_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString data_;

        /**
         * <code>bytes data = 4;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getNonceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nonce_);
            }
            if (gas_ != 0L) {
                output.writeUInt64(2, gas_);
            }
            if (value_ != 0L) {
                output.writeUInt64(3, value_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(4, data_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNonceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nonce_);
            }
            if (gas_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, gas_);
            }
            if (value_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeUInt64Size(3, value_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(4, data_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TransactionProto.Content)) {
                return super.equals(obj);
            }
            TransactionProto.Content other = (TransactionProto.Content) obj;

            boolean result = true;
            result = result && getNonce().equals(other.getNonce());
            result = result && (getGas() == other.getGas());
            result = result && (getValue() == other.getValue());
            result = result && getData().equals(other.getData());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NONCE_FIELD_NUMBER;
            hash = (53 * hash) + getNonce().hashCode();
            hash = (37 * hash) + GAS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getGas());
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getValue());
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TransactionProto.Content parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.Content parseFrom(com.google.protobuf.ByteString data,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.Content parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.Content parseFrom(byte[] data,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.Content parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.Content parseFrom(java.io.InputStream input,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TransactionProto.Content parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static TransactionProto.Content parseDelimitedFrom(java.io.InputStream input,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                                                                                        extensionRegistry);
        }

        public static TransactionProto.Content parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.Content parseFrom(com.google.protobuf.CodedInputStream input,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TransactionProto.Content prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Content}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Content)
                TransactionProto.ContentOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return TransactionProto.internal_static_Content_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return TransactionProto.internal_static_Content_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.Content.class,
                                                                                                                   TransactionProto.Content.Builder.class);
            }

            // Construct using com.ipaynow.sdk.api.dto.TransactionProto.Content.newBuilder()
            private Builder(){
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent){
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                nonce_ = "";

                gas_ = 0L;

                value_ = 0L;

                data_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return TransactionProto.internal_static_Content_descriptor;
            }

            public TransactionProto.Content getDefaultInstanceForType() {
                return TransactionProto.Content.getDefaultInstance();
            }

            public TransactionProto.Content build() {
                TransactionProto.Content result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TransactionProto.Content buildPartial() {
                TransactionProto.Content result = new TransactionProto.Content(this);
                result.nonce_ = nonce_;
                result.gas_ = gas_;
                result.value_ = value_;
                result.data_ = data_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TransactionProto.Content) {
                    return mergeFrom((TransactionProto.Content) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TransactionProto.Content other) {
                if (other == TransactionProto.Content.getDefaultInstance()) return this;
                if (!other.getNonce().isEmpty()) {
                    nonce_ = other.nonce_;
                    onChanged();
                }
                if (other.getGas() != 0L) {
                    setGas(other.getGas());
                }
                if (other.getValue() != 0L) {
                    setValue(other.getValue());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                TransactionProto.Content parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TransactionProto.Content) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object nonce_ = "";

            /**
             * <code>string nonce = 1;</code>
             */
            public java.lang.String getNonce() {
                java.lang.Object ref = nonce_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    nonce_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string nonce = 1;</code>
             */
            public com.google.protobuf.ByteString getNonceBytes() {
                java.lang.Object ref = nonce_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    nonce_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string nonce = 1;</code>
             */
            public Builder setNonce(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                nonce_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string nonce = 1;</code>
             */
            public Builder clearNonce() {

                nonce_ = getDefaultInstance().getNonce();
                onChanged();
                return this;
            }

            /**
             * <code>string nonce = 1;</code>
             */
            public Builder setNonceBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                nonce_ = value;
                onChanged();
                return this;
            }

            private long gas_;

            /**
             * <code>uint64 gas = 2;</code>
             */
            public long getGas() {
                return gas_;
            }

            /**
             * <code>uint64 gas = 2;</code>
             */
            public Builder setGas(long value) {

                gas_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 gas = 2;</code>
             */
            public Builder clearGas() {

                gas_ = 0L;
                onChanged();
                return this;
            }

            private long value_;

            /**
             * <code>uint64 value = 3;</code>
             */
            public long getValue() {
                return value_;
            }

            /**
             * <code>uint64 value = 3;</code>
             */
            public Builder setValue(long value) {

                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 value = 3;</code>
             */
            public Builder clearValue() {

                value_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes data = 4;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Content)
        }

        // @@protoc_insertion_point(class_scope:Content)
        private static final TransactionProto.Content DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new TransactionProto.Content();
        }

        public static TransactionProto.Content getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Content> PARSER = new com.google.protobuf.AbstractParser<Content>() {

            public Content parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Content(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Content> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Content> getParserForType() {
            return PARSER;
        }

        public TransactionProto.Content getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SignedTransactionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SignedTransaction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes transaction = 1;</code>
         */
        com.google.protobuf.ByteString getTransaction();

        /**
         * <code>bytes signature = 2;</code>
         */
        com.google.protobuf.ByteString getSignature();

        /**
         * <code>.Crypto crypto = 3;</code>
         */
        int getCryptoValue();

        /**
         * <code>.Crypto crypto = 3;</code>
         */
        TransactionProto.Crypto getCrypto();
    }

    /**
     * Protobuf type {@code SignedTransaction}
     */
    public static final class SignedTransaction extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:SignedTransaction)
            SignedTransactionOrBuilder {

        // Use SignedTransaction.newBuilder() to construct.
        private SignedTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder){
            super(builder);
        }

        private SignedTransaction(){
            transaction_ = com.google.protobuf.ByteString.EMPTY;
            signature_ = com.google.protobuf.ByteString.EMPTY;
            crypto_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private SignedTransaction(com.google.protobuf.CodedInputStream input,
                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException{
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {

                            transaction_ = input.readBytes();
                            break;
                        }
                        case 18: {

                            signature_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            crypto_ = rawValue;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return TransactionProto.internal_static_SignedTransaction_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return TransactionProto.internal_static_SignedTransaction_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.SignedTransaction.class,
                                                                                                                         TransactionProto.SignedTransaction.Builder.class);
        }

        public static final int                TRANSACTION_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString transaction_;

        /**
         * <code>bytes transaction = 1;</code>
         */
        public com.google.protobuf.ByteString getTransaction() {
            return transaction_;
        }

        public static final int                SIGNATURE_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString signature_;

        /**
         * <code>bytes signature = 2;</code>
         */
        public com.google.protobuf.ByteString getSignature() {
            return signature_;
        }

        public static final int CRYPTO_FIELD_NUMBER = 3;
        private int             crypto_;

        /**
         * <code>.Crypto crypto = 3;</code>
         */
        public int getCryptoValue() {
            return crypto_;
        }

        /**
         * <code>.Crypto crypto = 3;</code>
         */
        public TransactionProto.Crypto getCrypto() {
            TransactionProto.Crypto result = TransactionProto.Crypto.valueOf(crypto_);
            return result == null ? TransactionProto.Crypto.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!transaction_.isEmpty()) {
                output.writeBytes(1, transaction_);
            }
            if (!signature_.isEmpty()) {
                output.writeBytes(2, signature_);
            }
            if (crypto_ != TransactionProto.Crypto.SECP.getNumber()) {
                output.writeEnum(3, crypto_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!transaction_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, transaction_);
            }
            if (!signature_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, signature_);
            }
            if (crypto_ != TransactionProto.Crypto.SECP.getNumber()) {
                size += com.google.protobuf.CodedOutputStream.computeEnumSize(3, crypto_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TransactionProto.SignedTransaction)) {
                return super.equals(obj);
            }
            TransactionProto.SignedTransaction other = (TransactionProto.SignedTransaction) obj;

            boolean result = true;
            result = result && getTransaction().equals(other.getTransaction());
            result = result && getSignature().equals(other.getSignature());
            result = result && crypto_ == other.crypto_;
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
            hash = (53 * hash) + getTransaction().hashCode();
            hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
            hash = (53 * hash) + getSignature().hashCode();
            hash = (37 * hash) + CRYPTO_FIELD_NUMBER;
            hash = (53 * hash) + crypto_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TransactionProto.SignedTransaction parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.SignedTransaction parseFrom(com.google.protobuf.ByteString data,
                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.SignedTransaction parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TransactionProto.SignedTransaction parseFrom(byte[] data,
                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TransactionProto.SignedTransaction parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.SignedTransaction parseFrom(java.io.InputStream input,
                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TransactionProto.SignedTransaction parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static TransactionProto.SignedTransaction parseDelimitedFrom(java.io.InputStream input,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                                                                                        extensionRegistry);
        }

        public static TransactionProto.SignedTransaction parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static TransactionProto.SignedTransaction parseFrom(com.google.protobuf.CodedInputStream input,
                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TransactionProto.SignedTransaction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code SignedTransaction}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:SignedTransaction)
                TransactionProto.SignedTransactionOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return TransactionProto.internal_static_SignedTransaction_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return TransactionProto.internal_static_SignedTransaction_fieldAccessorTable.ensureFieldAccessorsInitialized(TransactionProto.SignedTransaction.class,
                                                                                                                             TransactionProto.SignedTransaction.Builder.class);
            }

            // Construct using com.ipaynow.sdk.api.dto.TransactionProto.SignedTransaction.newBuilder()
            private Builder(){
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent){
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                transaction_ = com.google.protobuf.ByteString.EMPTY;

                signature_ = com.google.protobuf.ByteString.EMPTY;

                crypto_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return TransactionProto.internal_static_SignedTransaction_descriptor;
            }

            public TransactionProto.SignedTransaction getDefaultInstanceForType() {
                return TransactionProto.SignedTransaction.getDefaultInstance();
            }

            public TransactionProto.SignedTransaction build() {
                TransactionProto.SignedTransaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TransactionProto.SignedTransaction buildPartial() {
                TransactionProto.SignedTransaction result = new TransactionProto.SignedTransaction(this);
                result.transaction_ = transaction_;
                result.signature_ = signature_;
                result.crypto_ = crypto_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TransactionProto.SignedTransaction) {
                    return mergeFrom((TransactionProto.SignedTransaction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TransactionProto.SignedTransaction other) {
                if (other == TransactionProto.SignedTransaction.getDefaultInstance()) return this;
                if (other.getTransaction() != com.google.protobuf.ByteString.EMPTY) {
                    setTransaction(other.getTransaction());
                }
                if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
                    setSignature(other.getSignature());
                }
                if (other.crypto_ != 0) {
                    setCryptoValue(other.getCryptoValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                TransactionProto.SignedTransaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TransactionProto.SignedTransaction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString transaction_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes transaction = 1;</code>
             */
            public com.google.protobuf.ByteString getTransaction() {
                return transaction_;
            }

            /**
             * <code>bytes transaction = 1;</code>
             */
            public Builder setTransaction(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transaction_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes transaction = 1;</code>
             */
            public Builder clearTransaction() {

                transaction_ = getDefaultInstance().getTransaction();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes signature = 2;</code>
             */
            public com.google.protobuf.ByteString getSignature() {
                return signature_;
            }

            /**
             * <code>bytes signature = 2;</code>
             */
            public Builder setSignature(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                signature_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes signature = 2;</code>
             */
            public Builder clearSignature() {

                signature_ = getDefaultInstance().getSignature();
                onChanged();
                return this;
            }

            private int crypto_ = 0;

            /**
             * <code>.Crypto crypto = 3;</code>
             */
            public int getCryptoValue() {
                return crypto_;
            }

            /**
             * <code>.Crypto crypto = 3;</code>
             */
            public Builder setCryptoValue(int value) {
                crypto_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.Crypto crypto = 3;</code>
             */
            public TransactionProto.Crypto getCrypto() {
                TransactionProto.Crypto result = TransactionProto.Crypto.valueOf(crypto_);
                return result == null ? TransactionProto.Crypto.UNRECOGNIZED : result;
            }

            /**
             * <code>.Crypto crypto = 3;</code>
             */
            public Builder setCrypto(TransactionProto.Crypto value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                crypto_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.Crypto crypto = 3;</code>
             */
            public Builder clearCrypto() {

                crypto_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            // @@protoc_insertion_point(builder_scope:SignedTransaction)
        }

        // @@protoc_insertion_point(class_scope:SignedTransaction)
        private static final TransactionProto.SignedTransaction DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new TransactionProto.SignedTransaction();
        }

        public static TransactionProto.SignedTransaction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SignedTransaction> PARSER = new com.google.protobuf.AbstractParser<SignedTransaction>() {

            public SignedTransaction parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new SignedTransaction(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SignedTransaction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SignedTransaction> getParserForType() {
            return PARSER;
        }

        public TransactionProto.SignedTransaction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_Transaction_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Transaction_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_Content_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Content_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_SignedTransaction_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_SignedTransaction_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\026transactionProto.proto\"8\n\013Transaction\022"
                                              + "\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007content\030\003 \001"
                                              + "(\014\"B\n\007Content\022\r\n\005nonce\030\001 \001(\t\022\013\n\003gas\030\002 \001("
                                              + "\004\022\r\n\005value\030\003 \001(\004\022\014\n\004data\030\004 \001(\014\"T\n\021Signed"
                                              + "Transaction\022\023\n\013transaction\030\001 \001(\014\022\021\n\tsign"
                                              + "ature\030\002 \001(\014\022\027\n\006crypto\030\003 \001(\0162\007.Crypto*\033\n\006"
                                              + "Crypto\022\010\n\004SECP\020\000\022\007\n\003SM2\020\001b\006proto3" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {

            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                                                                                      new com.google.protobuf.Descriptors.FileDescriptor[] {},
                                                                                      assigner);
        internal_static_Transaction_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Transaction_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Transaction_descriptor,
                                                                                                                       new java.lang.String[] { "From",
                                                                                                                                                "To", "Content", });
        internal_static_Content_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Content_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Content_descriptor,
                                                                                                                   new java.lang.String[] { "Nonce",
                                                                                                                                            "Gas", "Value", "Data", });
        internal_static_SignedTransaction_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_SignedTransaction_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_SignedTransaction_descriptor,
                                                                                                                             new java.lang.String[] { "Transaction",
                                                                                                                                                      "Signature", "Crypto", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
